// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sicoin.Contabilidad.Infrastructure.Persistence;

#nullable disable

namespace Sicoin.Contabilidad.Infrastructure.Migrations
{
    [DbContext(typeof(ContabilidadDbContext))]
    partial class ContabilidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.Comprobante", b =>
                {
                    b.Property<long>("ComprobanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("comprobante_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ComprobanteId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concepto");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsAutomatico")
                        .HasColumnType("boolean")
                        .HasColumnName("es_automatico");

                    b.Property<string>("EstadoComprobanteDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_comprobante_descripcion");

                    b.Property<int>("EstadoComprobanteId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_comprobante_id");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_contable");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gestion")
                        .HasColumnType("integer")
                        .HasColumnName("gestion");

                    b.Property<string>("MonedaDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_descripcion");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer")
                        .HasColumnName("moneda_id");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_anulacion");

                    b.Property<string>("NroComprobante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nro_comprobante");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_mes");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text")
                        .HasColumnName("referencia_externa");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer")
                        .HasColumnName("sucursal_id");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("numeric")
                        .HasColumnName("tipo_cambio");

                    b.Property<string>("TipoComprobanteDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_comprobante_descripcion");

                    b.Property<int>("TipoComprobanteId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_comprobante_id");

                    b.Property<decimal>("TotalDebe")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debe");

                    b.Property<decimal>("TotalHaber")
                        .HasColumnType("numeric")
                        .HasColumnName("total_haber");

                    b.Property<long?>("UsuarioModificacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("ComprobanteId");

                    b.ToTable("con_comprobantes");
                });

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.ComprobanteDetalle", b =>
                {
                    b.Property<long>("ComprobanteDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("comprobante_detalle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ComprobanteDetalleId"));

                    b.Property<string>("AuxiliarReferencia")
                        .HasColumnType("text")
                        .HasColumnName("auxiliar_referencia");

                    b.Property<int?>("CentroCostoId")
                        .HasColumnType("integer")
                        .HasColumnName("centro_costo_id");

                    b.Property<long>("ComprobanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("comprobante_id");

                    b.Property<long>("CuentaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cuenta_id");

                    b.Property<decimal>("Debe")
                        .HasColumnType("numeric")
                        .HasColumnName("debe");

                    b.Property<string>("Glosa")
                        .HasColumnType("text")
                        .HasColumnName("glosa");

                    b.Property<decimal>("Haber")
                        .HasColumnType("numeric")
                        .HasColumnName("haber");

                    b.Property<int>("NroLinea")
                        .HasColumnType("integer")
                        .HasColumnName("nro_linea");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.HasKey("ComprobanteDetalleId");

                    b.HasIndex("ComprobanteId");

                    b.HasIndex("CuentaId");

                    b.ToTable("con_comprobante_detalles");
                });

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.PlanCuenta", b =>
                {
                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<bool>("AceptaMoneda")
                        .HasColumnType("boolean")
                        .HasColumnName("acepta_moneda");

                    b.Property<bool>("AceptaMovimiento")
                        .HasColumnType("boolean")
                        .HasColumnName("acepta_movimiento");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoSinNandina")
                        .HasColumnType("text")
                        .HasColumnName("codigo_sin_nandina");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("N1")
                        .HasColumnType("integer")
                        .HasColumnName("n1");

                    b.Property<int?>("N2")
                        .HasColumnType("integer")
                        .HasColumnName("n2");

                    b.Property<int?>("N3")
                        .HasColumnType("integer")
                        .HasColumnName("n3");

                    b.Property<string>("N4")
                        .HasColumnType("text")
                        .HasColumnName("n4");

                    b.Property<string>("N5")
                        .HasColumnType("text")
                        .HasColumnName("n5");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.Property<long?>("PlanPadreId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_padre_id");

                    b.Property<bool>("RequiereCosto")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_costo");

                    b.Property<bool>("RequiereProyecto")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_proyecto");

                    b.Property<string>("SaldoNormalDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saldo_normal_descripcion");

                    b.Property<int>("SaldoNormalId")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_normal_id");

                    b.Property<string>("TipoCuentaDescripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_cuenta_descripcion");

                    b.Property<int>("TipoCuentaId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cuenta_id");

                    b.Property<long?>("UsuarioModificacionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioRegistroId")
                        .HasColumnType("bigint");

                    b.HasKey("PlanId");

                    b.HasIndex("PlanPadreId");

                    b.ToTable("con_planes_cuentas");
                });

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.ComprobanteDetalle", b =>
                {
                    b.HasOne("Sicoin.Contabilidad.Domain.Entities.Comprobante", "Comprobante")
                        .WithMany("Detalles")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sicoin.Contabilidad.Domain.Entities.PlanCuenta", "PlanCuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprobante");

                    b.Navigation("PlanCuenta");
                });

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.PlanCuenta", b =>
                {
                    b.HasOne("Sicoin.Contabilidad.Domain.Entities.PlanCuenta", null)
                        .WithMany("PlanesCuentasHijos")
                        .HasForeignKey("PlanPadreId");
                });

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.Comprobante", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Sicoin.Contabilidad.Domain.Entities.PlanCuenta", b =>
                {
                    b.Navigation("PlanesCuentasHijos");
                });
#pragma warning restore 612, 618
        }
    }
}
