using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sicoin.Contabilidad.Application.Interfaces;
using Sicoin.Contabilidad.Application.Services;
using Sicoin.Contabilidad.Domain.Entities;
using System;
using System.Threading.Tasks;

namespace Sicoin.Contabilidad.Api.Controllers;

[ApiController]
[Route("api/v1/cont/plan-cuentas")]
public class PlanCuentaController : ControllerBase
{
    private readonly IPlanCuentaService _planCuentaService;

    public PlanCuentaController(IPlanCuentaService planCuentaService)
    {
        _planCuentaService = planCuentaService;
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] PlanCuenta account, [FromQuery] Guid empresaId)
    {
        try
        {
            account.EmpresaId = empresaId;
            var createdAccount = await _planCuentaService.CreateAsync(account);
            return CreatedAtAction(nameof(GetTree), new { empresaId = account.EmpresaId }, createdAccount);
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = ex.Message });
        }
    }

    [HttpGet("tree/{empresaId:guid}")]
    public async Task<IActionResult> GetTree(Guid empresaId, [FromQuery] string? q = null)
    {
        try
        {
            var tree = await _planCuentaService.GetTreeAsync(empresaId, q);
            return Ok(tree);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { Message = ex.Message });
        }
    }

    [HttpGet("{planId}")]
    public async Task<IActionResult> GetById(long planId, [FromQuery] Guid empresaId)
    {
        try
        {
            var detail = await _planCuentaService.GetByIdAsync(planId, empresaId);
            if (detail == null) return NotFound();
            return Ok(detail);
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = ex.Message });
        }
    }

    [HttpPut("{planId}")]
    public async Task<IActionResult> Update(long planId, [FromBody] PlanCuenta account, [FromQuery] Guid empresaId)
    {
        try
        {
            account.PlanId = planId; // Ensure ID from path is used
            account.EmpresaId = empresaId; // Ensure company from query is used
            var updatedAccount = await _planCuentaService.UpdateAsync(account);
            return Ok(updatedAccount);
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = ex.Message });
        }
    }

    [HttpPost("importar/{empresaId:guid}")]
    public async Task<IActionResult> Importar(Guid empresaId, Microsoft.AspNetCore.Http.IFormFile file, [FromQuery] bool soloValidar = false, [FromQuery] bool sobreescribir = false)
    {
        try
        {
            if (file == null || file.Length == 0)
                return BadRequest(new { Message = "Archivo inválido o vacío." });

            using var stream = file.OpenReadStream();
            var result = await _planCuentaService.ImportarCuentasAnaliticasAsync(stream, empresaId, soloValidar, sobreescribir);
            return Ok(result);
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = "Error procesando el archivo: " + ex.Message });
        }
    }

    [HttpGet("seed/{empresaId:guid}")]
    public async Task<IActionResult> SeedPuctOficial(Guid empresaId, 
        [FromServices] PuctSeederService seeder,
        [FromServices] Sicoin.Contabilidad.Infrastructure.Persistence.ContabilidadDbContext db)
    {
        try
        {
            try { await db.Database.ExecuteSqlRawAsync("ALTER TABLE con_planes_cuentas ALTER COLUMN plan_id ADD GENERATED BY DEFAULT AS IDENTITY;"); } catch { }
            await seeder.SeedPuctOficialAsync(empresaId);
            return Ok(new { Message = "Siembre inicial del PUCT finalizada correctamente." });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { Message = "Error al sembrar el PUCT oficial: " + ex.Message });
        }
    }

    [HttpGet("movimiento/{empresaId:guid}")]
    public async Task<IActionResult> SearchCuentas(Guid empresaId, [FromQuery] string q = "")
    {
        try
        {
            var results = await _planCuentaService.SearchCuentasMovimientoAsync(empresaId, q);
            return Ok(results);
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = ex.Message });
        }
    }

    [HttpGet("con-centro-costo/{empresaId:guid}")]
    public async Task<IActionResult> GetCuentasConCentroCosto(Guid empresaId)
    {
        try
        {
            var results = await _planCuentaService.GetCuentasConCentroCostoAsync(empresaId);
            return Ok(results);
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = ex.Message });
        }
    }

    [HttpDelete("{planId}")]
    public async Task<IActionResult> Delete(long planId, [FromQuery] Guid empresaId)
    {
        try
        {
            await _planCuentaService.DeleteAsync(planId, empresaId);
            return Ok(new { Message = "Cuenta eliminada correctamente." });
        }
        catch (Exception ex)
        {
            return BadRequest(new { Message = ex.Message });
        }
    }
}

